export const exchanges = [
    {
      "id": "binance",
      "name": "Binance",
      "year_established": 2017,
      "country": "Cayman Islands",
      "description": "",
      "url": "https://www.binance.com/",
      "image": "https://assets.coingecko.com/markets/images/52/small/binance.jpg?1519353250",
      "has_trading_incentive": false,
      "trust_score": 10,
      "trust_score_rank": 1,
      "trade_volume_24h_btc": 414157.7196395655,
      "trade_volume_24h_btc_normalized": 278754.6160496111
    },
    {
      "id": "gdax",
      "name": "Coinbase Exchange",
      "year_established": 2012,
      "country": "United States",
      "description": "",
      "url": "https://www.coinbase.com",
      "image": "https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1621471875",
      "has_trading_incentive": false,
      "trust_score": 10,
      "trust_score_rank": 2,
      "trade_volume_24h_btc": 47457.230524624596,
      "trade_volume_24h_btc_normalized": 47457.230524624596
    },
    {
      "id": "kucoin",
      "name": "KuCoin",
      "year_established": 2014,
      "country": "Seychelles",
      "description": "",
      "url": "https://www.kucoin.com/",
      "image": "https://assets.coingecko.com/markets/images/61/small/kucoin.png?1640584259",
      "has_trading_incentive": false,
      "trust_score": 10,
      "trust_score_rank": 3,
      "trade_volume_24h_btc": 32023.76357066668,
      "trade_volume_24h_btc_normalized": 32023.76357066668
    },
    {
      "id": "kraken",
      "name": "Kraken",
      "year_established": 2011,
      "country": "United States",
      "description": "",
      "url": "https://r.kraken.com/c/2223866/687155/10583",
      "image": "https://assets.coingecko.com/markets/images/29/small/kraken.jpg?1584251255",
      "has_trading_incentive": false,
      "trust_score": 10,
      "trust_score_rank": 4,
      "trade_volume_24h_btc": 29708.385370505097,
      "trade_volume_24h_btc_normalized": 21169.785016890895
    },
    {
      "id": "bitfinex",
      "name": "Bitfinex",
      "year_established": 2014,
      "country": "British Virgin Islands",
      "description": "",
      "url": "https://www.bitfinex.com",
      "image": "https://assets.coingecko.com/markets/images/4/small/BItfinex.png?1615895883",
      "has_trading_incentive": false,
      "trust_score": 10,
      "trust_score_rank": 5,
      "trade_volume_24h_btc": 7258.739722601886,
      "trade_volume_24h_btc_normalized": 7258.739722601886
    },
    {
      "id": "mxc",
      "name": "MEXC Global",
      "year_established": 2018,
      "country": "Seychelles",
      "description": "Established in April 2018, MEXC Global is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.",
      "url": "https://www.mexc.com/",
      "image": "https://assets.coingecko.com/markets/images/409/small/MEXC_logo_square.jpeg?1673000123",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 6,
      "trade_volume_24h_btc": 39399.15779551418,
      "trade_volume_24h_btc_normalized": 37485.68002794113
    },
    {
      "id": "bybit_spot",
      "name": "Bybit",
      "year_established": 2018,
      "country": "British Virgin Islands",
      "description": "Bybit is a cryptocurrency exchange that offers a professional platform featuring an ultra-fast matching engine, excellent customer service and multilingual community support for crypto traders of all levels. Established in March 2018, Bybit currently serves more than 10 million users and institutions offering access to over 100 assets and contracts across Spot, Futures and Options, launchpad projects, earn products, an NFT Marketplace and more. Bybit is a proud partner of Formula One racing team, Oracle Red Bull Racing, esports teams NAVI, Astralis, Alliance, Virtus.pro, Made in Brazil (MIBR), City Esports, and Oracle Red Bull Racing Esports, and association football (soccer) teams Borussia Dortmund and Avispa Fukuoka.",
      "url": "https://www.bybit.com",
      "image": "https://assets.coingecko.com/markets/images/698/small/bybit_spot.png?1629971794",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 7,
      "trade_volume_24h_btc": 30347.00883787481,
      "trade_volume_24h_btc_normalized": 30347.00883787481
    },
    {
      "id": "okex",
      "name": "OKX",
      "year_established": 2017,
      "country": "Seychelles",
      "description": "",
      "url": "https://www.okx.com",
      "image": "https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1642428377",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 8,
      "trade_volume_24h_btc": 57028.775014548155,
      "trade_volume_24h_btc_normalized": 29295.39877271344
    },
    {
      "id": "bitget",
      "name": "Bitget",
      "year_established": 2018,
      "country": "Seychelles",
      "description": "",
      "url": "https://www.bitget.com/",
      "image": "https://assets.coingecko.com/markets/images/540/small/Bitget_new_logo_2.png?1630049618",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 9,
      "trade_volume_24h_btc": 26237.16025080828,
      "trade_volume_24h_btc_normalized": 26237.16025080828
    },
    {
      "id": "huobi",
      "name": "Huobi",
      "year_established": 2013,
      "country": "Seychelles",
      "description": "",
      "url": "https://www.huobi.com",
      "image": "https://assets.coingecko.com/markets/images/25/small/logo_V_colour_black.png?1669177364",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 10,
      "trade_volume_24h_btc": 18732.33552306627,
      "trade_volume_24h_btc_normalized": 18732.33552306627
    },
    {
      "id": "bingx",
      "name": "BingX",
      "year_established": 2018,
      "country": "United States",
      "description": "Founded in 2018, BingX is a crypto social trading exchange that offers spot, derivatives and copy trading services to more than 100 countries worldwide.\r\n\r\nBingX prides itself as the people's exchange by unlocking the fast-growing cryptocurrency market for everyone, connecting users with experts traders and a platform to invest in a simple, engaging and transparent way.",
      "url": "https://bingx.com/",
      "image": "https://assets.coingecko.com/markets/images/812/small/YtFwQwJr_400x400.jpg?1646056092",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 11,
      "trade_volume_24h_btc": 11414.017253619717,
      "trade_volume_24h_btc_normalized": 11414.017253619717
    },
    {
      "id": "crypto_com",
      "name": "Crypto.com Exchange",
      "year_established": 2019,
      "country": "Malta",
      "description": "Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards",
      "url": "https://crypto.com/exchange",
      "image": "https://assets.coingecko.com/markets/images/589/small/h2oMjPp6_400x400.jpg?1669699705",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 12,
      "trade_volume_24h_btc": 9987.584234587373,
      "trade_volume_24h_btc_normalized": 9987.584234587373
    },
    {
      "id": "binance_us",
      "name": "Binance US",
      "year_established": 2019,
      "country": "United States",
      "description": "",
      "url": "https://www.binance.us/",
      "image": "https://assets.coingecko.com/markets/images/469/small/Binance.png?1568875842",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 13,
      "trade_volume_24h_btc": 24878.064710267576,
      "trade_volume_24h_btc_normalized": 9436.821335742807
    },
    {
      "id": "phemex",
      "name": "Phemex",
      "year_established": 2019,
      "country": "Singapore",
      "description": "Launched in 2019, Phemex is a Singapore-based cryptocurrency and derivatives trading platform led by former Morgan Stanley executives. Serving around 5 million active users in over 200 countries, Phemex supports 150+ trading pairs with up to 100x leverage.\r\n\r\n-  Fee Structure: 0.1% for both maker and taker\r\n-  Contract Fee Structure: 0.01% for maker and 0.06% for taker\r\n-  Up to $100 Welcome Bonus for new users\r\n-  Earn up to 8.5% APY interest income on crypto assets\r\n-  Free academy with 450+ carefully curated articles about crypto & trading\r\n-  Security: Hierarchical Deterministic Cold Wallet System with 2-level human scrutiny offline signatures.",
      "url": "https://phemex.com/",
      "image": "https://assets.coingecko.com/markets/images/564/small/Phemex_logo_4.png?1641357471",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 14,
      "trade_volume_24h_btc": 4556.736238462273,
      "trade_volume_24h_btc_normalized": 4324.27857349982
    },
    {
      "id": "gemini",
      "name": "Gemini",
      "year_established": 2014,
      "country": "United States",
      "description": "",
      "url": "https://www.gemini.com/exchange",
      "image": "https://assets.coingecko.com/markets/images/50/small/gemini.png?1605704107",
      "has_trading_incentive": false,
      "trust_score": 9,
      "trust_score_rank": 15,
      "trade_volume_24h_btc": 1090.3642987500853,
      "trade_volume_24h_btc_normalized": 1090.3642987500853
    },
    {
      "id": "lbank",
      "name": "LBank",
      "year_established": 2015,
      "country": "British Virgin Islands",
      "description": "LBank is a globally based centralized exchange (CEX) platform established in 2015. The platform allows users to buy and sell major crypto assets like Bitcoin (BTC) and Ethereum (ETH) in over 149 fiat currencies, with over 20 payment methods. The company has licenses from the National Futures Association, Italian Organismo degli Agenti e dei Mediatori, and money services businesses in the United States & Canada. The LBank exchange has over 9 million users and accepts clients from over 200 regions.\r\nLBank Exchange provides its users with crypto trading, specialized financial derivatives, and professional asset management services.\r\n ",
      "url": "www.lbank.com",
      "image": "https://assets.coingecko.com/markets/images/118/small/LBank_logo.png?1666234663",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 16,
      "trade_volume_24h_btc": 51580.75979287697,
      "trade_volume_24h_btc_normalized": 43583.38169150658
    },
    {
      "id": "bitmart",
      "name": "BitMart",
      "year_established": 2017,
      "country": "Cayman Islands",
      "description": "",
      "url": "https://www.bitmart.com/en",
      "image": "https://assets.coingecko.com/markets/images/239/small/Bitmart.png?1628066397",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 17,
      "trade_volume_24h_btc": 30157.221862734736,
      "trade_volume_24h_btc_normalized": 30157.221862734736
    },
    {
      "id": "gate",
      "name": "Gate.io",
      "year_established": null,
      "country": "Cayman Islands",
      "description": "Gate was established in 2013, and it is the top 10 exchanges in the world in terms of authentic trading volume. It is also the first choice of over 8 million registered customers, covering 130+ countries worldwide, as we are providing the most comprehensive digital asset solutions.",
      "url": "https://gate.io/",
      "image": "https://assets.coingecko.com/markets/images/60/small/gate_io_logo1.jpg?1654596784",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 18,
      "trade_volume_24h_btc": 37625.781465170374,
      "trade_volume_24h_btc_normalized": 29357.531813033725
    },
    {
      "id": "bkex",
      "name": "BKEX",
      "year_established": 2018,
      "country": "British Virgin Islands",
      "description": "",
      "url": "https://www.bkex.com/",
      "image": "https://assets.coingecko.com/markets/images/293/small/New_BKEX_logo.png?1646724631",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 19,
      "trade_volume_24h_btc": 23586.883080645486,
      "trade_volume_24h_btc_normalized": 23586.883080645486
    },
    {
      "id": "whitebit",
      "name": "WhiteBIT",
      "year_established": 2018,
      "country": "Lithuania",
      "description": "",
      "url": "https://whitebit.com",
      "image": "https://assets.coingecko.com/markets/images/418/small/whitebit_final.png?1667923522",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 20,
      "trade_volume_24h_btc": 20419.327797327405,
      "trade_volume_24h_btc_normalized": 20419.327797327405
    },
    {
      "id": "digifinex",
      "name": "DigiFinex",
      "year_established": 2018,
      "country": "Seychelles",
      "description": "",
      "url": "https://www.digifinex.com/",
      "image": "https://assets.coingecko.com/markets/images/225/small/DF_logo.png?1594264355",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 21,
      "trade_volume_24h_btc": 17182.206682602133,
      "trade_volume_24h_btc_normalized": 17182.206682602133
    },
    {
      "id": "tidex",
      "name": "Tidex",
      "year_established": 2017,
      "country": "Lithuania",
      "description": "",
      "url": "https://tidex.com/",
      "image": "https://assets.coingecko.com/markets/images/43/small/favicon.png?1651817092",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 22,
      "trade_volume_24h_btc": 21671.71766519009,
      "trade_volume_24h_btc_normalized": 12475.64639910479
    },
    {
      "id": "btcex",
      "name": "BTCEX",
      "year_established": 2021,
      "country": "Seychelles",
      "description": "BTCEX is a highly extensible digital asset trading platform, which provides spot, spot leverage, futures, perpetual contracts, and USDT-settled options. In addition, it also supports multi-product portfolio margin models to improve the utilization of user funds.",
      "url": "https://www.btcex.com",
      "image": "https://assets.coingecko.com/markets/images/753/small/C8tiQdwL_400x400.jpg?1641348961",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 23,
      "trade_volume_24h_btc": 10958.233824500787,
      "trade_volume_24h_btc_normalized": 10958.233824500787
    },
    {
      "id": "p2pb2b",
      "name": "P2B",
      "year_established": 2018,
      "country": "Lithuania",
      "description": "P2B Cryptocurrency Exchange is one of the biggest European digital assets exchanges that has successfully operated for over 5 years. It is now the most trusted platform offering the best go-to-market experience for crypto users and projects.\r\n\r\nThe platform tops the most trusted ratings worldwide - CoinMarketCap and CoinGecko - and permanently improves its position. We assure the safety of the trading activities, being ranked in the TOP-12 in Cer.Live security rate. \r\n\r\nThe users can easily explore the mature crypto market by investing in a wide variety of liquid tokens, buying cryptocurrencies with bank cards (via Simplex, Moon Pay, Koinal) and using attractive discounts or bonuses during fundraising campaigns. You can also choose the amount of your commission,  - use the level commission to raise your account opportunities and make your trading more profitable. \r\n\r\nBecome a part of the prosperous P2B community - #1 place to be in crypto.\r\nGet your exciting trading experience with 24/7 support, and gain quickly and securely.\r\n",
      "url": "https://p2pb2b.com/",
      "image": "https://assets.coingecko.com/markets/images/251/small/ow0xng56_400x400.jpeg?1664939403",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 24,
      "trade_volume_24h_btc": 9169.34081592933,
      "trade_volume_24h_btc_normalized": 8659.755318262356
    },
    {
      "id": "bitstamp",
      "name": "Bitstamp",
      "year_established": 2013,
      "country": "Luxembourg",
      "description": "",
      "url": "https://links.bitstamp.net/c/2223866/1100037/14006",
      "image": "https://assets.coingecko.com/markets/images/9/small/bitstamp.jpg?1519627979",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 25,
      "trade_volume_24h_btc": 7109.933355088469,
      "trade_volume_24h_btc_normalized": 5296.394493205268
    },
    {
      "id": "coinstore",
      "name": "Coinstore",
      "year_established": 2020,
      "country": "Singapore",
      "description": "Coinstore was founded in 2020. There are 180 employees worldwide distributed mainly in Asia, Europe, and the Middle East, serving more than 1,500,000 registered users in 175 countries. Coinstore provides global users with fast and smooth cryptocurrency trading services, derivatives business, OTC services, and NFT services. Coinstore Labs provides project owners with integrated solutions of “technology development, compliance counseling, integrated marketing, community operations, investment incubation” and much more.\r\n\r\nCoinstore supports 102 spot pairs and 34 futures pairs. All features are available on Coinstore’s mobile app for iOS and Android, and on desktop.",
      "url": "https://www.coinstore.com/#/",
      "image": "https://assets.coingecko.com/markets/images/747/small/coinstore.jpeg?1639530357",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 26,
      "trade_volume_24h_btc": 6807.507872465199,
      "trade_volume_24h_btc_normalized": 5004.573943166835
    },
    {
      "id": "btcturk",
      "name": "BtcTurk PRO",
      "year_established": 2013,
      "country": "Turkey",
      "description": "",
      "url": "https://pro.btcturk.com/",
      "image": "https://assets.coingecko.com/markets/images/223/small/BTCTurk-exchange.jpg?1536726120",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 27,
      "trade_volume_24h_btc": 5114.656883765267,
      "trade_volume_24h_btc_normalized": 4609.0560858772515
    },
    {
      "id": "hotbit",
      "name": "Hotbit",
      "year_established": 2018,
      "country": "Hong Kong",
      "description": "Founded in 2018 and holding Estonian MTR licence, American MSB licence, an Australian AUSTRAC licence and a Canadian MSB licence，HotBit cryptocurrency exchange is known as a cryptocurrency trading platofrm that continues to develop and integrate various forms of businesses such as spot trading, financial derivatives, cryptocurrency investment and DAPP into one platform. Currently, Hotbit’s businesses covers more than 210 countries and areas. Based on its globalized and unified strategies, HotBit continues to focus on world's emerging markets such as Russia, Turkey and southeastern Asia markets, and was ranked one of the top 3 most welcomed exchanges by Russian media in 2019.",
      "url": "https://www.hotbit.io/",
      "image": "https://assets.coingecko.com/markets/images/201/small/hotbit.jpg?1531043195",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 28,
      "trade_volume_24h_btc": 4132.405742752848,
      "trade_volume_24h_btc_normalized": 4132.405742752848
    },
    {
      "id": "exmo",
      "name": "EXMO",
      "year_established": 2013,
      "country": "United Kingdom",
      "description": "",
      "url": "https://exmo.com/",
      "image": "https://assets.coingecko.com/markets/images/59/small/tt_ava.jpg?1669360697",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 29,
      "trade_volume_24h_btc": 3321.397134630391,
      "trade_volume_24h_btc_normalized": 3321.397134630391
    },
    {
      "id": "bitbank",
      "name": "Bitbank",
      "year_established": 2016,
      "country": "Japan",
      "description": "",
      "url": "https://bitbank.cc/",
      "image": "https://assets.coingecko.com/markets/images/122/small/bitbank.jpg?1521186278",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 30,
      "trade_volume_24h_btc": 2047.1509007124764,
      "trade_volume_24h_btc_normalized": 2047.1509007124764
    },
    {
      "id": "bitkub",
      "name": "Bitkub",
      "year_established": 2018,
      "country": "Thailand",
      "description": "",
      "url": "https://www.bitkub.com",
      "image": "https://assets.coingecko.com/markets/images/249/small/bitkub.png?1537180687",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 31,
      "trade_volume_24h_btc": 1710.0375264767417,
      "trade_volume_24h_btc_normalized": 1710.0375264767417
    },
    {
      "id": "coinex",
      "name": "CoinEx",
      "year_established": 2017,
      "country": "Samoa",
      "description": "",
      "url": "https://www.coinex.com/",
      "image": "https://assets.coingecko.com/markets/images/135/small/coinex.jpg?1527737297",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 32,
      "trade_volume_24h_btc": 1347.2898627315117,
      "trade_volume_24h_btc_normalized": 1347.2898627315117
    },
    {
      "id": "bitso",
      "name": "Bitso",
      "year_established": 2014,
      "country": "Gibraltar",
      "description": "",
      "url": "https://bitso.com",
      "image": "https://assets.coingecko.com/markets/images/8/small/Bitso-icon-dark.png?1581909156",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 33,
      "trade_volume_24h_btc": 1307.270303177384,
      "trade_volume_24h_btc_normalized": 1307.270303177384
    },
    {
      "id": "max_maicoin",
      "name": "Max Maicoin",
      "year_established": null,
      "country": "Taiwan",
      "description": "",
      "url": "https://max.maicoin.com",
      "image": "https://assets.coingecko.com/markets/images/218/small/max.jpg?1533888641",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 34,
      "trade_volume_24h_btc": 942.719702661629,
      "trade_volume_24h_btc_normalized": 942.719702661629
    },
    {
      "id": "bittrex",
      "name": "Bittrex",
      "year_established": 2014,
      "country": "Liechtenstein",
      "description": "",
      "url": "https://bittrex.com/",
      "image": "https://assets.coingecko.com/markets/images/10/small/BG-color-250x250_icon.png?1596167574",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 35,
      "trade_volume_24h_btc": 404.65940763503653,
      "trade_volume_24h_btc_normalized": 404.65940763503653
    },
    {
      "id": "blockchain_com",
      "name": "Blockchain.com",
      "year_established": 2012,
      "country": "United Kingdom",
      "description": "",
      "url": "https://www.blockchain.com/",
      "image": "https://assets.coingecko.com/markets/images/613/small/unnamedddd.png?1610503741",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 36,
      "trade_volume_24h_btc": 85.30812911411853,
      "trade_volume_24h_btc_normalized": 85.30812911411853
    },
    {
      "id": "coinspro",
      "name": "Coins.ph",
      "year_established": null,
      "country": "Philippines",
      "description": "",
      "url": "https://coins.ph/about",
      "image": "https://assets.coingecko.com/markets/images/999/small/coinspro.png?1668488887",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 37,
      "trade_volume_24h_btc": 21.890651337749443,
      "trade_volume_24h_btc_normalized": 21.890651337749443
    },
    {
      "id": "bitmex_spot",
      "name": "BitMEX",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://www.bitmex.com/spot/",
      "image": "https://assets.coingecko.com/markets/images/866/small/bitmex.jpeg?1652794708",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 38,
      "trade_volume_24h_btc": 18.803987232597326,
      "trade_volume_24h_btc_normalized": 18.803987232597326
    },
    {
      "id": "nice_hash",
      "name": "NiceHash",
      "year_established": null,
      "country": "Slovenia",
      "description": "",
      "url": "https://www.nicehash.com",
      "image": "https://assets.coingecko.com/markets/images/546/small/logo_small_light.png?1637836622",
      "has_trading_incentive": false,
      "trust_score": 8,
      "trust_score_rank": 39,
      "trade_volume_24h_btc": 10.001221210608207,
      "trade_volume_24h_btc_normalized": 10.001221210608207
    },
    {
      "id": "upbit",
      "name": "Upbit",
      "year_established": 2017,
      "country": "South Korea",
      "description": "",
      "url": "https://upbit.com",
      "image": "https://assets.coingecko.com/markets/images/117/small/upbit.png?1520388800",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 40,
      "trade_volume_24h_btc": 120252.5434498878,
      "trade_volume_24h_btc_normalized": 34101.87111802248
    },
    {
      "id": "bitrue",
      "name": "Bitrue",
      "year_established": 2018,
      "country": "Singapore",
      "description": "",
      "url": "https://www.bitrue.com/",
      "image": "https://assets.coingecko.com/markets/images/254/small/unnamed_%281%29.png?1656295820",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 41,
      "trade_volume_24h_btc": 65312.27404637432,
      "trade_volume_24h_btc_normalized": 26157.93238935634
    },
    {
      "id": "coinsbit",
      "name": "Coinsbit",
      "year_established": null,
      "country": "Estonia",
      "description": "",
      "url": "https://coinsbit.io/",
      "image": "https://assets.coingecko.com/markets/images/267/small/Coinsbit.png?1605153697",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 42,
      "trade_volume_24h_btc": 16105.116780813889,
      "trade_volume_24h_btc_normalized": 16105.116780813889
    },
    {
      "id": "bithumb",
      "name": "Bithumb",
      "year_established": 2014,
      "country": "South Korea",
      "description": "",
      "url": "https://www.bithumb.com/",
      "image": "https://assets.coingecko.com/markets/images/6/small/bithumb_BI.png?1573104549",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 43,
      "trade_volume_24h_btc": 14462.365121936931,
      "trade_volume_24h_btc_normalized": 12968.775413598196
    },
    {
      "id": "deepcoin",
      "name": "Deepcoin",
      "year_established": 2018,
      "country": "Seychelles",
      "description": "Deepcoin Exchange offers groundbreaking tools for you to buy and sell over 120 cryptocurrencies. Since 2018, we have provided a secure and reliable way for you to invest in spot and futures trading to our over 1 million users.",
      "url": "https://www.deepcoin.com/",
      "image": "https://assets.coingecko.com/markets/images/1005/small/%E2%98%85%E6%96%B9-%E9%80%8F%E6%98%8E7.png?1678175660",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 44,
      "trade_volume_24h_btc": 12546.666946589266,
      "trade_volume_24h_btc_normalized": 9855.254118433915
    },
    {
      "id": "bigone",
      "name": "BigONE",
      "year_established": 2017,
      "country": "Netherlands",
      "description": "",
      "url": "https://bigone.com",
      "image": "https://assets.coingecko.com/markets/images/100/small/qcFFufEY_400x400.jpg?1561103345",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 45,
      "trade_volume_24h_btc": 6049.63821578311,
      "trade_volume_24h_btc_normalized": 6049.63821578311
    },
    {
      "id": "dextrade",
      "name": "Dex-Trade",
      "year_established": 2019,
      "country": "Belize",
      "description": "Dex-Trade is a centralized cryptocurrency exchange founded in 2017 and registered in Belize. This is a modern space for safe and comfortable trading with minimal commissions.\r\n\r\nDex-Trade is a universal exchange for both beginners and professional traders. The minimum spread and high liquidity in order books allow you to trade efficiently with orders of any volume.\r\nAlong with global opportunities, the exchange also provides a demo trading mode for risk-free testing of your trading strategies. Our dedicated support team is online 24/7 to assist you with any questions.\r\n\r\nYou can learn more about Dex-Trade on the website.\r\nhttps://dex-trade.com/info/about\r\n\r\nIf you are looking for listing and promotion options with Dex-Trade please visit our listing page and a personal manager will help you to utilize our proven tools and intelligent market-making system to engage with the vast exchange community in the best possible way. https://dex-trade.com/listing",
      "url": "https://dex-trade.com/",
      "image": "https://assets.coingecko.com/markets/images/380/small/Dex-Trade_logo_new.png?1599629803",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 46,
      "trade_volume_24h_btc": 5601.630562824746,
      "trade_volume_24h_btc_normalized": 5601.630562824746
    },
    {
      "id": "paribu",
      "name": "Paribu",
      "year_established": null,
      "country": "Turkey",
      "description": null,
      "url": "https://www.paribu.com/",
      "image": "https://assets.coingecko.com/markets/images/136/small/paribu.jpg?1527734779",
      "has_trading_incentive": null,
      "trust_score": 7,
      "trust_score_rank": 47,
      "trade_volume_24h_btc": 4099.845484286216,
      "trade_volume_24h_btc_normalized": 4099.845484286216
    },
    {
      "id": "bitflyer",
      "name": "bitFlyer",
      "year_established": 2014,
      "country": "Japan",
      "description": "",
      "url": "https://bitflyereuropesa.pxf.io/c/2223866/858437/11990",
      "image": "https://assets.coingecko.com/markets/images/5/small/bitFlyer-logo.png?1643256033",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 48,
      "trade_volume_24h_btc": 3871.1616010274097,
      "trade_volume_24h_btc_normalized": 3871.1616010274097
    },
    {
      "id": "latoken",
      "name": "LATOKEN",
      "year_established": 2017,
      "country": "Cayman Islands",
      "description": "",
      "url": "https://latoken.com/",
      "image": "https://assets.coingecko.com/markets/images/124/small/LA_token.png?1605773251",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 49,
      "trade_volume_24h_btc": 5569.813987267649,
      "trade_volume_24h_btc_normalized": 2629.242682273225
    },
    {
      "id": "coincheck",
      "name": "Coincheck",
      "year_established": 2014,
      "country": "Japan",
      "description": null,
      "url": "https://coincheck.com/",
      "image": "https://assets.coingecko.com/markets/images/18/small/Coincheck.jpg?1519703836",
      "has_trading_incentive": null,
      "trust_score": 7,
      "trust_score_rank": 50,
      "trade_volume_24h_btc": 2050.273869944176,
      "trade_volume_24h_btc_normalized": 2050.273869944176
    },
    {
      "id": "poloniex",
      "name": "Poloniex",
      "year_established": 2014,
      "country": "Seychelles",
      "description": "Poloniex was founded in January 2014 as a global cryptocurrency exchange. It provides spot trading, futures trading, staking, and various services to users in nearly 100 countries and regions with various languages available.\r\n\r\nIn 2022, Poloniex launched a brand new trading system to provide global retail and professional users with higher speed, as well as better stability and usability.",
      "url": "https://poloniex.com/",
      "image": "https://assets.coingecko.com/markets/images/37/small/poloniex.png?1663310089",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 51,
      "trade_volume_24h_btc": 1978.2826147257765,
      "trade_volume_24h_btc_normalized": 1978.2826147257765
    },
    {
      "id": "bitmax",
      "name": "AscendEX (BitMax)",
      "year_established": 2018,
      "country": "Singapore",
      "description": "AscendEX (formerly BitMax) is a leading global digital asset financial platform founded by a group of Wall Street quantitative trading veterans in 2018, building on core value of “Efficiency, Resilience and Transparency.” \r\n \r\nDriven by its continuous innovative product development and early-mover advantage in strategic alignment with the leading projects from DeFi ecosystem, AscendEX offers trading services across over 200 trading pairs across cash, margin, and futures products, in particular margin trading of over 50 tokens in cross-asset collateral mode and futures trading in both cross-asset and isolated margin modes.",
      "url": "https://ascendex.com/en/global-digital-asset-platform",
      "image": "https://assets.coingecko.com/markets/images/277/small/%E5%8E%9F%E8%89%B2.png?1650557355",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 52,
      "trade_volume_24h_btc": 9339.015334685146,
      "trade_volume_24h_btc_normalized": 1011.8008938455006
    },
    {
      "id": "luno",
      "name": "Luno",
      "year_established": 2013,
      "country": "Singapore",
      "description": "",
      "url": "https://www.luno.com",
      "image": "https://assets.coingecko.com/markets/images/33/small/luno.jpg?1519996997",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 53,
      "trade_volume_24h_btc": 866.5199452637695,
      "trade_volume_24h_btc_normalized": 866.5199452637695
    },
    {
      "id": "bit_com",
      "name": "BIT",
      "year_established": 2020,
      "country": "Seychelles",
      "description": "",
      "url": "https://www.bit.com/",
      "image": "https://assets.coingecko.com/markets/images/823/small/bit_old.jpg?1669104460",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 54,
      "trade_volume_24h_btc": 3204.1181133380787,
      "trade_volume_24h_btc_normalized": 781.1689027327535
    },
    {
      "id": "wootrade",
      "name": "WOO X",
      "year_established": 2019,
      "country": "Seychelles",
      "description": "WOO Network is a deep liquidity network connecting traders, exchanges, institutions, and DeFi platforms with democratized access to the best-in-class liquidity and trading execution at lower or zero cost. Its flagship, WOO X, is a professional trading platform featuring customizable modules and lower to zero fees complete with deep liquidity. WOO Network was founded by Kronos Research, a quantitative trading firm generating $5-10B in daily volume.",
      "url": "https://woo.org/",
      "image": "https://assets.coingecko.com/markets/images/683/small/woo.png?1677468948",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 55,
      "trade_volume_24h_btc": 2502.686030195584,
      "trade_volume_24h_btc_normalized": 733.8810760327282
    },
    {
      "id": "independent_reserve",
      "name": "Independent Reserve",
      "year_established": 2013,
      "country": "Australia",
      "description": "",
      "url": "https://www.independentreserve.com/",
      "image": "https://assets.coingecko.com/markets/images/389/small/x_V5Jquo_400x400.png?1556071437",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 56,
      "trade_volume_24h_btc": 724.8910298309808,
      "trade_volume_24h_btc_normalized": 700.2132870669482
    },
    {
      "id": "kanga",
      "name": "Kanga",
      "year_established": 2018,
      "country": "Belize",
      "description": "",
      "url": "https://kanga.exchange/",
      "image": "https://assets.coingecko.com/markets/images/852/small/kanga_logo.png?1650269423",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 57,
      "trade_volume_24h_btc": 382.5915150787064,
      "trade_volume_24h_btc_normalized": 382.5915150787064
    },
    {
      "id": "indodax",
      "name": "Indodax",
      "year_established": 2014,
      "country": "Indonesia",
      "description": "",
      "url": "https://indodax.com",
      "image": "https://assets.coingecko.com/markets/images/3/small/logogram-Indodax-new-_JPG_format.jpg?1580974378",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 58,
      "trade_volume_24h_btc": 353.28676273951754,
      "trade_volume_24h_btc_normalized": 353.28676273951754
    },
    {
      "id": "bitopro",
      "name": "BitoPro",
      "year_established": 2018,
      "country": "Taiwan",
      "description": "",
      "url": "https://www.bitopro.com/",
      "image": "https://assets.coingecko.com/markets/images/358/small/bitopro_coingecko_250x250_%281%29.png?1575884378",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 59,
      "trade_volume_24h_btc": 412.5121437491687,
      "trade_volume_24h_btc_normalized": 341.130434274578
    },
    {
      "id": "finexbox",
      "name": "FinexBox",
      "year_established": 2018,
      "country": "Hong Kong",
      "description": "",
      "url": "https://www.finexbox.com/",
      "image": "https://assets.coingecko.com/markets/images/318/small/finexbox20190920.jpg?1568959220",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 60,
      "trade_volume_24h_btc": 323.0601308806053,
      "trade_volume_24h_btc_normalized": 323.0601308806053
    },
    {
      "id": "btcmarkets",
      "name": "BTCMarkets",
      "year_established": null,
      "country": "Australia",
      "description": "",
      "url": "https://www.btcmarkets.net/",
      "image": "https://assets.coingecko.com/markets/images/237/small/BTCMarkets_logo2.png?1677732205",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 61,
      "trade_volume_24h_btc": 309.5012586734365,
      "trade_volume_24h_btc_normalized": 309.5012586734365
    },
    {
      "id": "bitpanda",
      "name": "Bitpanda Pro",
      "year_established": 2019,
      "country": "Austria",
      "description": "",
      "url": "https://exchange.bitpanda.com",
      "image": "https://assets.coingecko.com/markets/images/474/small/appicon-ios-pro.png?1622626638",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 62,
      "trade_volume_24h_btc": 279.9884414423458,
      "trade_volume_24h_btc_normalized": 279.9884414423458
    },
    {
      "id": "korbit",
      "name": "Korbit",
      "year_established": 2013,
      "country": "South Korea",
      "description": "",
      "url": "https://www.korbit.co.kr/",
      "image": "https://assets.coingecko.com/markets/images/28/small/korbit-logo.png?1584091827",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 63,
      "trade_volume_24h_btc": 268.92643782992155,
      "trade_volume_24h_btc_normalized": 268.92643782992155
    },
    {
      "id": "okcoin",
      "name": "Okcoin",
      "year_established": 2013,
      "country": "United States",
      "description": "Founded in 2013, Okcoin is a US-headquartered cryptocurrency exchange serving 190+ countries and territories. The platform enables retail and institutional investors to purchase digital assets using local currencies, with a mission to make crypto easy for everyone, including first-time buyers. Okcoin was the first centralized exchange to offer direct entry into decentralized finance (DeFi) with Earn, a tool for earning APY through decentralized lending, liquidity pools, staking, and more. In addition, Okcoin offers institutional trading tools and APIs to asset managers, venture capital and hedge funds, retail brokers, payment processors, and more. Follow Okcoin on Twitter at @Okcoin and visit okcoin.com for more information.",
      "url": "https://www.okcoin.com/",
      "image": "https://assets.coingecko.com/markets/images/415/small/okcoin_Logomark_SatoshiBlack.png?1619574335",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 64,
      "trade_volume_24h_btc": 129.95673134005963,
      "trade_volume_24h_btc_normalized": 129.95673134005963
    },
    {
      "id": "coin_metro",
      "name": "Coinmetro",
      "year_established": 2018,
      "country": "Estonia",
      "description": "",
      "url": "https://coinmetro.com/",
      "image": "https://assets.coingecko.com/markets/images/386/small/Coinmetro_Exchange_Logo_%282%29.png?1646280101",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 65,
      "trade_volume_24h_btc": 36.50550179411801,
      "trade_volume_24h_btc_normalized": 36.50550179411801
    },
    {
      "id": "kuna",
      "name": "Kuna Exchange",
      "year_established": null,
      "country": "United Kingdom",
      "description": "",
      "url": "https://kuna.io/",
      "image": "https://assets.coingecko.com/markets/images/97/small/kuna_exchange.png?1545126178",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 66,
      "trade_volume_24h_btc": 29.017558838177514,
      "trade_volume_24h_btc_normalized": 29.017558838177514
    },
    {
      "id": "delta_spot",
      "name": "Delta Exchange",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://www.delta.exchange/app/spot/trade/",
      "image": "https://assets.coingecko.com/markets/images/642/small/delta_spot.jpg?1617283005",
      "has_trading_incentive": false,
      "trust_score": 7,
      "trust_score_rank": 67,
      "trade_volume_24h_btc": 15.221936807061113,
      "trade_volume_24h_btc_normalized": 15.221936807061113
    },
    {
      "id": "xt",
      "name": "XT.COM",
      "year_established": 2018,
      "country": "Seychelles",
      "description": "By consistently expanding its ecosystem, XT.COM is dedicated to providing users with the most secure, trusted, and hassle-free digital asset trading services. Our exchange is built from a desire to give everyone access to digital assets regardless where you are. \r\n\r\nFounded in 2018, XT.COM now serves more than 6 million registered users, over 500,000+ monthly active users and 40+ million users in the ecosystem. Covering a rich variety of  trading categories together with a NFT aggregated marketplace,  our platform strives to cater to its large user base by providing a secure, trusted and intuitive trading experience.\r\n\r\nAs the world’s first social-infused digital assets trading platform, XT.COM also supports social networking platform based transactions to make our crypto services more accessible to users all over the world. Furthermore, to ensure optimal data integrity and security, we see user security as our top priority at XT.COM. ",
      "url": "https://www.xt.com/",
      "image": "https://assets.coingecko.com/markets/images/404/small/logo400x400.png?1575881839",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 68,
      "trade_volume_24h_btc": 22136.706937206174,
      "trade_volume_24h_btc_normalized": 22136.706937206174
    },
    {
      "id": "uniswap_v3_arbitrum",
      "name": "Uniswap (Arbitrum One)",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://app.uniswap.org/#/swap",
      "image": "https://assets.coingecko.com/markets/images/702/small/uniswap-v3.png?1631616149",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 69,
      "trade_volume_24h_btc": 13120.724388537363,
      "trade_volume_24h_btc_normalized": 13120.724388537363
    },
    {
      "id": "probit",
      "name": "ProBit Global",
      "year_established": 2017,
      "country": "Seychelles",
      "description": "",
      "url": "https://www.probit.com/",
      "image": "https://assets.coingecko.com/markets/images/370/small/probit.png?1594886584",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 70,
      "trade_volume_24h_btc": 4436.494652315761,
      "trade_volume_24h_btc_normalized": 4436.494652315761
    },
    {
      "id": "pancakeswap_new",
      "name": "PancakeSwap (v2)",
      "year_established": 2020,
      "country": null,
      "description": "",
      "url": "https://pancakeswap.finance",
      "image": "https://assets.coingecko.com/markets/images/687/small/pancakeswap.jpeg?1626060212",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 71,
      "trade_volume_24h_btc": 4187.114752723529,
      "trade_volume_24h_btc_normalized": 4187.114752723529
    },
    {
      "id": "pionex",
      "name": "Pionex",
      "year_established": 2019,
      "country": "British Virgin Islands",
      "description": "",
      "url": "https://www.pionex.com",
      "image": "https://assets.coingecko.com/markets/images/1026/small/pionex.png?1673508138",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 72,
      "trade_volume_24h_btc": 14152.673000450526,
      "trade_volume_24h_btc_normalized": 3889.831477887946
    },
    {
      "id": "bitvavo",
      "name": "Bitvavo",
      "year_established": 2018,
      "country": "Netherlands",
      "description": "",
      "url": "https://bitvavo.com/en",
      "image": "https://assets.coingecko.com/markets/images/714/small/bitvavo-mark-square-black.png?1633688872",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 73,
      "trade_volume_24h_btc": 3767.056076225946,
      "trade_volume_24h_btc_normalized": 3767.056076225946
    },
    {
      "id": "uniswap_v3_polygon_pos",
      "name": "Uniswap (Polygon)",
      "year_established": 2021,
      "country": null,
      "description": "",
      "url": "https://app.uniswap.org/#/swap",
      "image": "https://assets.coingecko.com/markets/images/752/small/uniswap-polygon.png?1640329417",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 74,
      "trade_volume_24h_btc": 2288.7114323100795,
      "trade_volume_24h_btc_normalized": 2288.7114323100795
    },
    {
      "id": "cryptology",
      "name": "Cryptology",
      "year_established": 2018,
      "country": "Lithuania",
      "description": "",
      "url": "https://cryptology.com/",
      "image": "https://assets.coingecko.com/markets/images/287/small/logo-symbol.png?1669975181",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 75,
      "trade_volume_24h_btc": 1904.6299887299413,
      "trade_volume_24h_btc_normalized": 1904.6299887299413
    },
    {
      "id": "bitexen",
      "name": "Bitexen",
      "year_established": 2018,
      "country": null,
      "description": "",
      "url": "https://www.bitexen.com/",
      "image": "https://assets.coingecko.com/markets/images/693/small/Bitexen_Logo_Short.png?1634198471",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 76,
      "trade_volume_24h_btc": 2031.424076945262,
      "trade_volume_24h_btc_normalized": 1708.5185239093448
    },
    {
      "id": "traderjoe-v2-arbitrum",
      "name": "Trader Joe v2 (Arbitrum)",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://traderjoexyz.com/arbitrum/trade",
      "image": "https://assets.coingecko.com/markets/images/1031/small/TraderJoe.png?1674093818",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 77,
      "trade_volume_24h_btc": 1511.1717422124334,
      "trade_volume_24h_btc_normalized": 1511.1717422124334
    },
    {
      "id": "traderjoe-v2-avalanche",
      "name": "Trader Joe v2",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://traderjoexyz.com/avalanche/trade",
      "image": "https://assets.coingecko.com/markets/images/1030/small/TraderJoe.png?1674093446",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 78,
      "trade_volume_24h_btc": 1333.999752079138,
      "trade_volume_24h_btc_normalized": 1333.999752079138
    },
    {
      "id": "sushiswap",
      "name": "Sushiswap",
      "year_established": 2020,
      "country": null,
      "description": "",
      "url": "https://app.sushi.com/swap",
      "image": "https://assets.coingecko.com/markets/images/576/small/2048x2048_Logo.png?1609208464",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 79,
      "trade_volume_24h_btc": 1385.4934596400874,
      "trade_volume_24h_btc_normalized": 1075.36064497716
    },
    {
      "id": "gmo_japan",
      "name": "GMO Japan",
      "year_established": null,
      "country": "Japan",
      "description": "",
      "url": "https://coin.z.com/jp/",
      "image": "https://assets.coingecko.com/markets/images/430/small/gmo_z_com.png?1561112572",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 80,
      "trade_volume_24h_btc": 852.9797676390352,
      "trade_volume_24h_btc_normalized": 852.9797676390352
    },
    {
      "id": "orca",
      "name": "Orca",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://www.orca.so/",
      "image": "https://assets.coingecko.com/markets/images/691/small/orca.png?1628047248",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 81,
      "trade_volume_24h_btc": 553.0463050752192,
      "trade_volume_24h_btc_normalized": 553.0463050752192
    },
    {
      "id": "bitbns",
      "name": "BitBNS",
      "year_established": 2017,
      "country": "Estonia",
      "description": "",
      "url": "https://ref.bitbns.com/",
      "image": "https://assets.coingecko.com/markets/images/541/small/HS7eNJdt_400x400.jpg?1592294824",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 82,
      "trade_volume_24h_btc": 545.3678702218499,
      "trade_volume_24h_btc_normalized": 545.3678702218499
    },
    {
      "id": "velodrome",
      "name": "Velodrome Finance",
      "year_established": 2022,
      "country": null,
      "description": "Velodrome Finance, at its core, is a solution for protocols on Optimism to properly incentivize liquidity for their own use cases. Building on top of the groundwork laid out by Solidly, our team has addressed that first iteration's core issues to realize its full potential.\r\n\r\nThe team behind Velodrome Finance previously launched veDAO, an initiative incubated by Information Token. veDAO's founding mandate was to engage with the Solidly ecosystem, a protocol launched on the Fantom network by Andre Cronje, while driving long-term value to the veDAO community.\r\n\r\nThe veDAO team has since developed deep subject matter expertise on both Solidly, the veNFT primitive, and the ve(3,3) mechanism, becoming the go-to resource for protocols and chains seeking support around these topics.",
      "url": "https://app.velodrome.finance/swap",
      "image": "https://assets.coingecko.com/markets/images/933/small/velodrome-finance.png?1660261754",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 83,
      "trade_volume_24h_btc": 495.5595923660002,
      "trade_volume_24h_btc_normalized": 495.5595923660002
    },
    {
      "id": "dodo_bsc",
      "name": "Dodo (BSC)",
      "year_established": 2021,
      "country": null,
      "description": "",
      "url": "https://dodoex.io/",
      "image": "https://assets.coingecko.com/markets/images/640/small/41tgsq69_400x400.png?1618372654",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 84,
      "trade_volume_24h_btc": 471.56513783543073,
      "trade_volume_24h_btc_normalized": 471.56513783543073
    },
    {
      "id": "camelot",
      "name": "Camelot",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://camelot.exchange/",
      "image": "https://assets.coingecko.com/markets/images/1007/small/vj5DIMhP_400x400.jpeg?1670561015",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 85,
      "trade_volume_24h_btc": 466.57242914915986,
      "trade_volume_24h_btc_normalized": 466.57242914915986
    },
    {
      "id": "btse",
      "name": "BTSE",
      "year_established": 2018,
      "country": "British Virgin Islands",
      "description": "BTSE is a leading digital asset exchange that empowers users by offering a simple and secure way to trade. Its growing suite of financial services is designed to bridge traditional finance with digital assets solutions. BTSE's innovative technology offers a set of digital financial solutions featuring multi-currency spot and derivatives trading, in addition to NFT and exchange white labels, over-the-counter (OTC) trading, asset management, and payment gateways. Additionally, BTSE provides an all-in-one order book, strict security protocols, an insurance fund, cold storage for more than 99% of assets and no withdrawal limits on over 12 fiat currencies and 100 cryptocurrencies.",
      "url": "https://www.btse.com/",
      "image": "https://assets.coingecko.com/markets/images/464/small/BTSE.jpg?1568012415",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 86,
      "trade_volume_24h_btc": 21660.238119863167,
      "trade_volume_24h_btc_normalized": 414.1125111877246
    },
    {
      "id": "pancakeswap_stableswap",
      "name": "Pancakeswap (Stableswap)",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://pancakeswap.finance/swap",
      "image": "https://assets.coingecko.com/markets/images/1035/small/pancakeswap.jpeg?1674702488",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 87,
      "trade_volume_24h_btc": 399.1868668257348,
      "trade_volume_24h_btc_normalized": 399.1868668257348
    },
    {
      "id": "nominex",
      "name": "Nominex",
      "year_established": 2019,
      "country": "Seychelles",
      "description": "New trading platform for convenient trading experience with low fees and numerous instruments. \r\n\r\nAbsolutely unique affiliate program that allows to earn from an infinite number of referral levels, compared to 2-3 levels at all other exchanges. \r\n\r\nA unique model for the free 2 phases distribution of the native NMX token.\r\n\r\nAdvanced Trading Instruments – using Stop, Stop Limit, Trailing Stop, Scaled and other types of orders brings some kind of trading automation without the need to develop a trading bot, which allows to easily get more profit while trading.",
      "url": "https://www.nominex.io",
      "image": "https://assets.coingecko.com/markets/images/530/small/logo-200x200.png?1587543672",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 88,
      "trade_volume_24h_btc": 922.7501815540044,
      "trade_volume_24h_btc_normalized": 358.93630243712283
    },
    {
      "id": "thena",
      "name": "Thena",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://thena.fi/swap",
      "image": "https://assets.coingecko.com/markets/images/1039/small/thena.png?1675060616",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 89,
      "trade_volume_24h_btc": 342.88269233010146,
      "trade_volume_24h_btc_normalized": 342.88269233010146
    },
    {
      "id": "tokenize",
      "name": "Tokenize",
      "year_established": 2018,
      "country": "Singapore",
      "description": "",
      "url": "https://tokenize.exchange/",
      "image": "https://assets.coingecko.com/markets/images/383/small/tokenize-exchange.png?1586138532",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 90,
      "trade_volume_24h_btc": 1070.9352340692774,
      "trade_volume_24h_btc_normalized": 312.29449672739224
    },
    {
      "id": "defi_swap",
      "name": "DeFi Swap",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://crypto.com/defi/swap",
      "image": "https://assets.coingecko.com/markets/images/637/small/crypto-com-mco-coin-logo.png?1616490722",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 91,
      "trade_volume_24h_btc": 310.50304746852265,
      "trade_volume_24h_btc_normalized": 310.50304746852265
    },
    {
      "id": "sushiswap_arbitrum",
      "name": "Sushiswap (Arbitrum One)",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://app.sushi.com/swap",
      "image": "https://assets.coingecko.com/markets/images/701/small/sushiswap3.png?1631339015",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 92,
      "trade_volume_24h_btc": 308.04425910352745,
      "trade_volume_24h_btc_normalized": 308.04425910352745
    },
    {
      "id": "bitazza",
      "name": "Bitazza",
      "year_established": 2021,
      "country": null,
      "description": "Bitazza is ASEAN's locally-based digital asset platform. ",
      "url": "https://trade.bitazza.com/gl/exchange/",
      "image": "https://assets.coingecko.com/markets/images/837/small/btzlogo200x200_darkgreen.png?1648702264",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 93,
      "trade_volume_24h_btc": 295.203385129499,
      "trade_volume_24h_btc_normalized": 295.203385129499
    },
    {
      "id": "osmosis",
      "name": "Osmosis",
      "year_established": 2021,
      "country": null,
      "description": "Osmosis is an automated market maker (AMM) protocol built for liquidity providers. It is built based on the Cosmos SDK and is the first dex for IBC tokens.",
      "url": "https://app.osmosis.zone/",
      "image": "https://assets.coingecko.com/markets/images/684/small/osmosis-dex.jpeg?1624850295",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 94,
      "trade_volume_24h_btc": 282.2858733085154,
      "trade_volume_24h_btc_normalized": 282.2858733085154
    },
    {
      "id": "spookyswap",
      "name": "SpookySwap",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://spookyswap.finance/swap",
      "image": "https://assets.coingecko.com/markets/images/662/small/spookyswap.png?1639279823",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 95,
      "trade_volume_24h_btc": 266.11007481901424,
      "trade_volume_24h_btc_normalized": 266.11007481901424
    },
    {
      "id": "klayswap",
      "name": "KLAYSwap",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://klayswap.com/exchange/swap",
      "image": "https://assets.coingecko.com/markets/images/1008/small/klayswap.jpeg?1670810834",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 96,
      "trade_volume_24h_btc": 211.1920520324568,
      "trade_volume_24h_btc_normalized": 211.1920520324568
    },
    {
      "id": "cex",
      "name": "CEX.IO",
      "year_established": 2013,
      "country": "United Kingdom",
      "description": "",
      "url": "https://cex.io/",
      "image": "https://assets.coingecko.com/markets/images/56/small/main-icon.png?1617267530",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 97,
      "trade_volume_24h_btc": 203.10620111205304,
      "trade_volume_24h_btc_normalized": 203.10620111205304
    },
    {
      "id": "dodo_polygon",
      "name": "Dodo (Polygon)",
      "year_established": null,
      "country": null,
      "description": "",
      "url": "https://app.dodoex.io/",
      "image": "https://assets.coingecko.com/markets/images/709/small/dodo_logo.png?1633078678",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 98,
      "trade_volume_24h_btc": 192.06314422635378,
      "trade_volume_24h_btc_normalized": 192.06314422635378
    },
    {
      "id": "katana",
      "name": "Katana",
      "year_established": 2021,
      "country": null,
      "description": "",
      "url": "https://katana.roninchain.com/#/swap",
      "image": "https://assets.coingecko.com/markets/images/731/small/ronin-katana.png?1636437019",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 99,
      "trade_volume_24h_btc": 162.16502701288016,
      "trade_volume_24h_btc_normalized": 162.16502701288016
    },
    {
      "id": "wazirx",
      "name": "WazirX",
      "year_established": 2018,
      "country": "India",
      "description": "",
      "url": "https://wazirx.com/",
      "image": "https://assets.coingecko.com/markets/images/274/small/wazirx.jpg?1540450020",
      "has_trading_incentive": false,
      "trust_score": 6,
      "trust_score_rank": 100,
      "trade_volume_24h_btc": 107.90599010376727,
      "trade_volume_24h_btc_normalized": 107.90599010376727
    }
  ]